# Generated by Django 2.2.1 on 2020-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Citizenship',
            field=models.CharField(choices=[('US citizen', 'US citizen'), ('Permanent Resident', 'Permanent Resident'), ('Student Visa', 'Student Visa')], default='', max_length=50),
        ),
    ]
