# Generated by Django 2.1.1 on 2020-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Upload',
            field=models.FileField(blank=True, max_length=256, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='dob',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
