# Generated by Django 2.2.1 on 2020-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201210_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Citizenship',
            field=models.CharField(blank=True, choices=[('US citizen', 'US citizen'), ('Permanent Resident', 'Permanent Resident'), ('Student Visa', 'Student Visa')], default='', max_length=50, null=True),
        ),
    ]
