# Generated by Django 2.2.1 on 2020-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201210_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Citizenship',
            field=models.CharField(blank=True, choices=[('US citizen', 'US citizen'), ('Permanent Resident', 'Permanent Resident'), ('Student Visa', 'Student Visa')], default='US citizen', max_length=50, null=True),
        ),
    ]
