# Generated by Django 2.1.1 on 2020-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201016_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_1',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_2',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_3',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_4',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_5',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_6',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
