# Generated by Django 2.1.1 on 2020-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_1',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_2',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_3',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_4',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_5',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_6',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
