# Generated by Django 2.1.1 on 2020-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201016_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Dates_Attended_7',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_expected_7',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
