# Generated by Django 2.1.1 on 2020-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201016_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cheque_no',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
