# Generated by Django 2.1.1 on 2020-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201019_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Citizenship',
            field=models.CharField(blank=True, choices=[('US citizen', 'US citizen'), ('Permanent Resident', 'Permanent Resident'), ('Student Visa', 'Student Visa')], default='US citizen', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100),
        ),
    ]
