# Generated by Django 2.1.1 on 2020-10-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20201024_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(choices=[('5 – Outstanding', '5 – Outstanding'), ('4.5', '4.5'), ('4 – Very Good', '4 – Very Good'), ('3.5', '3.5'), ('3 – Good', '3 – Good'), ('2.5', '2.5'), ('2 – Poor', '2 – Poor'), ('1.5', '1.5'), ('1 – Not worthy of funding', '1 – Not worthy of funding')], max_length=25)),
                ('stat', models.CharField(choices=[('Evaluation Saved', 'Save for later submission'), ('Evaluation Completed', 'Final submission')], max_length=25)),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Applicant')),
                ('eval_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
