# Generated by Django 2.1.1 on 2020-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='ranking',
            field=models.CharField(choices=[('5', '5 – Outstanding'), ('4.5', '4.5'), ('4', '4 – Very Good'), ('3.5', '3.5'), ('3', '3 – Good'), ('2.5', '2.5'), ('2', '2 – Poor'), ('1.5', '1.5'), ('1', '1 – Not worthy of funding')], max_length=25),
        ),
    ]
